### PR TITLE
Update AgIsoStack

### PR DESCRIPTION
**Pull request by ad3154**
## What's New

-- Updated the version of AgIsoStack++ to [867d2c0d02a31f97c17aab2d17970f650db1bf8e](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/commit/867d2c0d02a31f97c17aab2d17970f650db1bf8e)

This update includes months of improvements and new features!

Some features include:

- Better TP and ETP conformance with ISO11783
- Language command improvements
- Added ways to trigger an update of your device descriptor object pool
- Added ISO11783-11 references
- Fixed a number of issues with NMEA2000
- Added a VT client state tracker which can help you develop more advanced VT projects
- General bug fixes

Visit us on the [main repo](https://github.com/Open-Agriculture/AgIsoStack-plus-plus) for more information.

Join us on [Discord](https://discord.gg/uU2XMVUD4b) for support, to share your project, and good vibes in general! Alternatively, you can also join us on [Telegram](https://t.me/+kzd4-9Je5bo1ZDg6).

### CODE REVIEW

**Review by GwnDaan — APPROVED** [review]
I'd be a bit hesitant about the versioning, since we're introducing a lot of breaking changes but just increasing the patch version (considering [semantic versioning](https://semver.org/)). Though I also don't like ending up with different versions for the arduino library and main library... Not sure what's best here

**Comment by ad3154** [comment]
Yeah, I'm really not sure what to do with the version... We broken enough stuff to where increasing the major version probably makes sense, but I don't know if I like "1.0.0" for a project with an unstable API.... I dunno. Ideally it would be nice to sync the two repo's versions

**Comment by GwnDaan** [comment]
Yeahh, let's just stick with this for now. Or increase the version to 0.2, idk... I think keeping the major version 0 for now keeps us able to sync it with the main branch

**Comment by ad3154** [comment]
OK... I had picked .4 to realign the arduino version with the git tag version. IDK why they are out of sync...

**Pull request merged**
